---
name: WorkflowHello

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Hello World
        run:  echo "Hello World"
        shell: bash
